### PR TITLE
Fix quantity types

### PR DESCRIPTION
**Pull request by ladinesa**

### CODE REVIEW

**Comment by TLCFEM** [comment]
The changes made to shapes may correct the related issue.

There are 9 changes in 02e110d4221fc80144c89cce73918db8f7c65274

For type mismatch, is it necessary to change the parsers as well?

**Comment by ladinesa** [comment]
I suggest we rebase your branch [type-mismatch](https://github.com/nomad-coe/nomad-schema-plugin-run/compare/type-mismatch) to the current develop and reference this in NOMAD before we merge it here otherwise we would have errors in tests here because it is running NOMAD develop for tests. But I personally would not want to have these no type checks.

**Comment by ladinesa** [comment]
I am trying to fix the issues now in 1947-run

**Comment by TLCFEM** [comment]
> I suggest we rebase your branch [type-mismatch](https://github.com/nomad-coe/nomad-schema-plugin-run/compare/type-mismatch) to the current develop and reference this in NOMAD before we merge it here otherwise we would have errors in tests here because it is running NOMAD develop for tests. But I personally would not want to have these no type checks.

It shall work before and after the change of typing system so yeah better with no check bypassing. Just like the other two, this repo does not necessarily need to be aware of the new typing system. It is easier to work on 1947-run I guess.

When it is fixed in this repo, I'll merge 1947-run into 1947, and 1947 will eventually be merged into develop. But I guess a rebase is needed before merging into develop. Thus whether you want to separately update the referenced commit of this repo in nomad develop is up to you. I'll keep an eye on it.

**Pull request merged**
